default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubilling_development

test:
  <<: *default
  database: <%= ENV.fetch('PG_DATABASE', 'postgres') %> 
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', nil) %>
  password: <%= ENV.fetch('PG_PASSWORD', nil) %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>

production:
  <<: *default
  database: rubilling_production
  username: rubilling
  password: <%= ENV['YOUR_APP_NAME_HERE_DATABASE_PASSWORD'] %>
